using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VendingStock.Api.Common;
using VendingStock.Api.Contracts;
using VendingStock.Api.Infrastructure;
namespace VendingStock.Api.Controllers;
[ApiController][Route("api/v1/vending-machine/{machineId:long}/product")]
public sealed class MachineProductsController(VendingStockDbContext db):ControllerBase
{
 [HttpGet("list")] public async Task<ApiResponse> List(long machineId,CancellationToken ct){var products=await db.MachineProducts.AsNoTracking().Where(x=>x.MachineId==machineId).Include(x=>x.Product).ThenInclude(x=>x.Spec).Include(x=>x.Product).ThenInclude(x=>x.Brand).OrderBy(x=>x.Product.Name).ToListAsync(ct);return ApiResponse.Ok(products.Select(x=>new{x.Id,x.ProductId,ProductName=x.Product.Name,SpecName=x.Product.Spec.Name,BrandName=x.Product.Brand.Name,x.StockQuantity,x.AllocationQuantity,x.SellPrice,StockRate=x.AllocationQuantity==0?0:Math.Round(x.StockQuantity*100m/x.AllocationQuantity,2)}));}
 [HttpPost] public async Task<ApiResponse> Create(long machineId,MachineProductRequest r,CancellationToken ct){await Verify(machineId,r.ProductId,ct);if(r.StockQuantity<0||r.AllocationQuantity<0||r.SellPrice<0)throw new BusinessException("机器商品参数不合法");if(await db.MachineProducts.AnyAsync(x=>x.MachineId==machineId&&x.ProductId==r.ProductId,ct))throw new BusinessException("该机器已配置该商品");var x=new Domain.MachineProduct{MachineId=machineId,ProductId=r.ProductId,StockQuantity=r.StockQuantity,AllocationQuantity=r.AllocationQuantity,SellPrice=r.SellPrice};db.MachineProducts.Add(x);await db.SaveChangesAsync(ct);return ApiResponse.Ok(new{id=x.Id});}
 [HttpPut("{id:long}")] public async Task<ApiResponse> Update(long machineId,long id,MachineProductUpdateRequest r,CancellationToken ct){var x=await db.MachineProducts.SingleOrDefaultAsync(x=>x.Id==id&&x.MachineId==machineId,ct)??throw new BusinessException("机器商品不存在",4040);if(r.StockQuantity<0||r.AllocationQuantity<0||r.SellPrice<0)throw new BusinessException("机器商品参数不合法");x.StockQuantity=r.StockQuantity;x.AllocationQuantity=r.AllocationQuantity;x.SellPrice=r.SellPrice;await db.SaveChangesAsync(ct);return ApiResponse.Ok();}
 [HttpDelete("{id:long}")] public async Task<ApiResponse> Delete(long machineId,long id,CancellationToken ct){var x=await db.MachineProducts.SingleOrDefaultAsync(x=>x.Id==id&&x.MachineId==machineId,ct)??throw new BusinessException("机器商品不存在",4040);db.MachineProducts.Remove(x);await db.SaveChangesAsync(ct);return ApiResponse.Ok();}
 [HttpGet("/api/v1/vending-machine/{machineId:long}/restock-suggestion")] public async Task<ApiResponse> Suggestion(long machineId,CancellationToken ct){var thresholdText=await db.SysConfigs.Where(x=>x.ConfigKey=="restock_threshold_percent").Select(x=>x.ConfigValue).SingleOrDefaultAsync(ct)??"50";var threshold=decimal.TryParse(thresholdText,out var value)?value:50;var products=await db.MachineProducts.AsNoTracking().Where(x=>x.MachineId==machineId&&x.AllocationQuantity>0&&x.StockQuantity*100m/x.AllocationQuantity<threshold).Include(x=>x.Product).ThenInclude(x=>x.Spec).ToListAsync(ct);return ApiResponse.Ok(new{ThresholdPercent=threshold,Items=products.Select(x=>new{x.ProductId,ProductName=x.Product.Name,SpecName=x.Product.Spec.Name,x.StockQuantity,x.AllocationQuantity,SuggestedQuantity=x.AllocationQuantity-x.StockQuantity})});}
 private async Task Verify(long machineId,long productId,CancellationToken ct){if(!await db.VendingMachines.AnyAsync(x=>x.Id==machineId,ct)||!await db.Products.AnyAsync(x=>x.Id==productId,ct))throw new BusinessException("贩卖机或商品不存在");}
}
