using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VendingStock.Api.Common;
using VendingStock.Api.Contracts;
using VendingStock.Api.Domain;
using VendingStock.Api.Infrastructure;
namespace VendingStock.Api.Controllers;
[ApiController][Route("api/v1")]
public sealed class ResourceDetailsController(VendingStockDbContext db):ControllerBase
{
 [HttpGet("warehouse/{id:long}")] public async Task<ApiResponse> Warehouse(long id,CancellationToken ct){var x=await db.Warehouses.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("仓库不存在",4040);return ApiResponse.Ok(new{x.Id,x.Name,x.Address,x.Manager,x.ManagerPhone});}
 [HttpGet("warehouse-stock/{id:long}")] public async Task<ApiResponse> Stock(long id,CancellationToken ct){var x=await db.WarehouseStocks.AsNoTracking().Include(x=>x.Warehouse).Include(x=>x.Product).ThenInclude(x=>x.Spec).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("库存记录不存在",4040);return ApiResponse.Ok(new{x.Id,x.WarehouseId,WarehouseName=x.Warehouse.Name,x.ProductId,ProductName=x.Product.Name,SpecName=x.Product.Spec.Name,x.Quantity,x.Tags});}
 [HttpGet("staff/{id:long}")] public async Task<ApiResponse> Staff(long id,CancellationToken ct){var x=await db.StaffMembers.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("人员不存在",4040);return ApiResponse.Ok(new{x.Id,x.Name,x.Phone,x.Address,x.Role});}
 [HttpGet("vehicle/{id:long}")] public async Task<ApiResponse> Vehicle(long id,CancellationToken ct){var x=await db.Vehicles.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("车辆不存在",4040);return ApiResponse.Ok(new{x.Id,x.PlateNumber,x.VehicleType});}
 [HttpGet("delivery-order/{id:long}")] public async Task<ApiResponse> Delivery(long id,CancellationToken ct){var x=await db.DeliveryOrders.AsNoTracking().Include(x=>x.Machine).Include(x=>x.Restocker).Include(x=>x.DeliveryPerson).Include(x=>x.Vehicle).Include(x=>x.Items).ThenInclude(x=>x.Product).Include(x=>x.Items).ThenInclude(x=>x.SourceWarehouse).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("配货单不存在",4040);return ApiResponse.Ok(new{x.Id,x.OrderNo,x.MachineId,MachineCode=x.Machine.MachineCode,x.RestockerId,RestockerName=x.Restocker.Name,x.DeliveryPersonId,DeliveryPersonName=x.DeliveryPerson.Name,x.VehicleId,VehiclePlate=x.Vehicle==null?null:x.Vehicle.PlateNumber,x.Status,x.CompletedTime,x.DeliveryStartTime,x.DeliveryEndTime,x.CancelledTime,x.CancelReason,Items=x.Items.Select(i=>new{i.Id,i.ProductId,ProductName=i.Product.Name,i.SourceWarehouseId,WarehouseName=i.SourceWarehouse.Name,i.Quantity})});}
 [HttpPut("purchase-order/{id:long}")] public async Task<ApiResponse> UpdatePurchase(long id,PurchaseOrderRequest r,CancellationToken ct){var x=await db.PurchaseOrders.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("进货单不存在",4040);if(x.Status==PurchaseOrderStatus.Imported)throw new BusinessException("已入库进货单不可编辑");if(r.Items.Count==0||r.Items.Any(i=>i.Quantity<=0)||!await db.Warehouses.AnyAsync(w=>w.Id==r.WarehouseId,ct))throw new BusinessException("进货单参数不合法");var ids=r.Items.Select(i=>i.ProductId).ToArray();if(ids.Distinct().Count()!=ids.Length||await db.Products.CountAsync(p=>ids.Contains(p.Id),ct)!=ids.Length)throw new BusinessException("进货商品不存在或重复");x.WarehouseId=r.WarehouseId;x.ImportTime=r.ImportTime;x.DeliveryPerson=r.DeliveryPerson.Trim();x.Receiver=r.Receiver.Trim();x.TotalQuantity=r.Items.Sum(i=>i.Quantity);db.PurchaseOrderItems.RemoveRange(x.Items);x.Items=r.Items.Select(i=>new PurchaseOrderItem{ProductId=i.ProductId,Quantity=i.Quantity}).ToList();await db.SaveChangesAsync(ct);return ApiResponse.Ok();}
 [HttpPut("delivery-order/{id:long}")] public async Task<ApiResponse> UpdateDelivery(long id,DeliveryOrderUpdateRequest r,CancellationToken ct){var x=await db.DeliveryOrders.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("配货单不存在",4040);if(x.Status!=DeliveryOrderStatus.Pending)throw new BusinessException("仅待配货单可编辑");if(r.Items.Count==0||r.Items.Any(i=>i.Quantity<=0)||r.Items.Select(i=>i.ProductId).Distinct().Count()!=r.Items.Count)throw new BusinessException("配货明细不合法");if(!await db.VendingMachines.AnyAsync(i=>i.Id==x.MachineId,ct)||!await db.StaffMembers.AnyAsync(i=>i.Id==r.RestockerId&&i.Role==StaffRole.Restocker,ct)||!await db.StaffMembers.AnyAsync(i=>i.Id==r.DeliveryPersonId&&i.Role==StaffRole.DeliveryPerson,ct)||r.VehicleId.HasValue&&!await db.Vehicles.AnyAsync(i=>i.Id==r.VehicleId,ct))throw new BusinessException("配货单关联信息不合法");x.RestockerId=r.RestockerId;x.DeliveryPersonId=r.DeliveryPersonId;x.VehicleId=r.VehicleId;db.DeliveryOrderItems.RemoveRange(x.Items);x.Items=r.Items.Select(i=>new DeliveryOrderItem{ProductId=i.ProductId,SourceWarehouseId=i.SourceWarehouseId,Quantity=i.Quantity}).ToList();await db.SaveChangesAsync(ct);return ApiResponse.Ok();}
}
