using Microsoft.EntityFrameworkCore;
using VendingStock.Api.Domain;
namespace VendingStock.Api.Infrastructure;
public sealed class VendingStockDbContext(DbContextOptions<VendingStockDbContext> options) : DbContext(options)
{
 public DbSet<ProductCategory> ProductCategories => Set<ProductCategory>(); public DbSet<ProductSpec> ProductSpecs => Set<ProductSpec>(); public DbSet<ProductBrand> ProductBrands => Set<ProductBrand>(); public DbSet<Product> Products => Set<Product>(); public DbSet<Warehouse> Warehouses => Set<Warehouse>(); public DbSet<WarehouseStock> WarehouseStocks => Set<WarehouseStock>(); public DbSet<PurchaseOrder> PurchaseOrders => Set<PurchaseOrder>(); public DbSet<PurchaseOrderItem> PurchaseOrderItems => Set<PurchaseOrderItem>(); public DbSet<InventoryTransaction> InventoryTransactions => Set<InventoryTransaction>(); public DbSet<VendingMachine> VendingMachines => Set<VendingMachine>(); public DbSet<MachineProduct> MachineProducts => Set<MachineProduct>(); public DbSet<Staff> StaffMembers => Set<Staff>(); public DbSet<Vehicle> Vehicles => Set<Vehicle>(); public DbSet<DeliveryOrder> DeliveryOrders => Set<DeliveryOrder>(); public DbSet<DeliveryOrderItem> DeliveryOrderItems => Set<DeliveryOrderItem>(); public DbSet<SysConfig> SysConfigs => Set<SysConfig>(); public DbSet<ProductRaw> ProductRaws => Set<ProductRaw>(); public DbSet<SyncTaskLog> SyncTaskLogs => Set<SyncTaskLog>(); public DbSet<DailySales> DailySales => Set<DailySales>();
 protected override void OnModelCreating(ModelBuilder b) { base.OnModelCreating(b);
  b.Entity<ProductCategory>(e=>{e.ToTable("product_category");e.Property(x=>x.Name).HasMaxLength(50);e.HasIndex(x=>x.Name).IsUnique();});
  b.Entity<ProductSpec>(e=>{e.ToTable("product_spec");e.Property(x=>x.Name).HasMaxLength(50);e.HasIndex(x=>x.Name).IsUnique();});
  b.Entity<ProductBrand>(e=>{e.ToTable("product_brand");e.Property(x=>x.Name).HasMaxLength(100);e.HasIndex(x=>x.Name).IsUnique();});
  b.Entity<Product>(e => { e.ToTable("product"); e.Property(x=>x.Name).HasMaxLength(100); e.Property(x=>x.Price).HasPrecision(10,2); e.Property(x=>x.ImageUrl).HasMaxLength(500); e.HasIndex(x=>new{x.Name,x.SpecId,x.BrandId}).IsUnique(); e.HasIndex(x=>x.CategoryId); e.HasOne(x=>x.Spec).WithMany(x=>x.Products).HasForeignKey(x=>x.SpecId); e.HasOne(x=>x.Brand).WithMany(x=>x.Products).HasForeignKey(x=>x.BrandId); e.HasOne(x=>x.Category).WithMany(x=>x.Products).HasForeignKey(x=>x.CategoryId); });
  b.Entity<Warehouse>(e=>{e.ToTable("warehouse"); e.Property(x=>x.Name).HasMaxLength(100); e.Property(x=>x.Address).HasMaxLength(200); e.Property(x=>x.Manager).HasMaxLength(50); e.Property(x=>x.ManagerPhone).HasMaxLength(20);});
  b.Entity<WarehouseStock>(e=>{e.ToTable("warehouse_stock"); e.Property(x=>x.Tags).HasMaxLength(500); e.HasIndex(x=>new{x.WarehouseId,x.ProductId}).IsUnique(); e.HasIndex(x=>x.ProductId); e.HasOne(x=>x.Warehouse).WithMany(x=>x.Stocks).HasForeignKey(x=>x.WarehouseId); e.HasOne(x=>x.Product).WithMany().HasForeignKey(x=>x.ProductId);});
  b.Entity<PurchaseOrder>(e=>{e.ToTable("purchase_order"); e.Property(x=>x.OrderNo).HasMaxLength(32); e.HasIndex(x=>x.OrderNo).IsUnique(); e.HasIndex(x=>new{x.WarehouseId,x.Status}); e.Property(x=>x.DeliveryPerson).HasMaxLength(50); e.Property(x=>x.Receiver).HasMaxLength(50); e.HasOne(x=>x.Warehouse).WithMany().HasForeignKey(x=>x.WarehouseId);});
  b.Entity<PurchaseOrderItem>(e=>{e.ToTable("purchase_order_item");e.HasIndex(x=>x.ProductId);e.HasOne(x=>x.Order).WithMany(x=>x.Items).HasForeignKey(x=>x.OrderId).OnDelete(DeleteBehavior.Cascade);e.HasOne(x=>x.Product).WithMany().HasForeignKey(x=>x.ProductId);});
  b.Entity<InventoryTransaction>(e=>{e.ToTable("inventory_transaction");e.Property(x=>x.RelatedOrderNo).HasMaxLength(32);e.Property(x=>x.Remark).HasMaxLength(500);e.HasIndex(x=>new{x.WarehouseId,x.ProductId});});
  b.Entity<VendingMachine>(e=>{e.ToTable("vending_machine");e.Property(x=>x.MachineCode).HasMaxLength(50);e.Property(x=>x.Address).HasMaxLength(200);e.Property(x=>x.Manager).HasMaxLength(50);e.Property(x=>x.ManagerPhone).HasMaxLength(20);e.HasIndex(x=>x.MachineCode).IsUnique();});
  b.Entity<MachineProduct>(e=>{e.ToTable("machine_product");e.Property(x=>x.SellPrice).HasPrecision(10,2);e.HasIndex(x=>new{x.MachineId,x.ProductId}).IsUnique();e.HasIndex(x=>x.ProductId);e.HasOne(x=>x.Machine).WithMany(x=>x.Products).HasForeignKey(x=>x.MachineId);e.HasOne(x=>x.Product).WithMany().HasForeignKey(x=>x.ProductId);});
  b.Entity<Staff>(e=>{e.ToTable("staff");e.Property(x=>x.Name).HasMaxLength(50);e.Property(x=>x.Phone).HasMaxLength(20);e.Property(x=>x.Address).HasMaxLength(200);e.HasIndex(x=>x.Role);});
  b.Entity<Vehicle>(e=>{e.ToTable("vehicle");e.Property(x=>x.PlateNumber).HasMaxLength(20);e.Property(x=>x.VehicleType).HasMaxLength(50);e.HasIndex(x=>x.PlateNumber).IsUnique();});
  b.Entity<DeliveryOrder>(e=>{e.ToTable("delivery_order");e.Property(x=>x.OrderNo).HasMaxLength(32);e.Property(x=>x.CancelReason).HasMaxLength(500);e.HasIndex(x=>x.OrderNo).IsUnique();e.HasIndex(x=>new{x.MachineId,x.Status});e.HasIndex(x=>x.RestockerId);e.HasIndex(x=>x.DeliveryPersonId);e.HasOne(x=>x.Machine).WithMany().HasForeignKey(x=>x.MachineId);e.HasOne(x=>x.Restocker).WithMany().HasForeignKey(x=>x.RestockerId).OnDelete(DeleteBehavior.Restrict);e.HasOne(x=>x.DeliveryPerson).WithMany().HasForeignKey(x=>x.DeliveryPersonId).OnDelete(DeleteBehavior.Restrict);e.HasOne(x=>x.Vehicle).WithMany().HasForeignKey(x=>x.VehicleId).OnDelete(DeleteBehavior.SetNull);});
  b.Entity<DeliveryOrderItem>(e=>{e.ToTable("delivery_order_item");e.HasIndex(x=>x.ProductId);e.HasIndex(x=>x.SourceWarehouseId);e.HasOne(x=>x.Order).WithMany(x=>x.Items).HasForeignKey(x=>x.OrderId).OnDelete(DeleteBehavior.Cascade);e.HasOne(x=>x.Product).WithMany().HasForeignKey(x=>x.ProductId);e.HasOne(x=>x.SourceWarehouse).WithMany().HasForeignKey(x=>x.SourceWarehouseId);});
  b.Entity<SysConfig>(e=>{e.ToTable("sys_config");e.Property(x=>x.ConfigKey).HasMaxLength(100);e.Property(x=>x.ConfigValue).HasMaxLength(500);e.Property(x=>x.Description).HasMaxLength(200);e.HasIndex(x=>x.ConfigKey).IsUnique();e.HasData(new SysConfig{Id=1,ConfigKey="restock_threshold_percent",ConfigValue="50",Description="补货阈值百分比(低于此比例需补货)",CreatedAt=new DateTime(2026,1,1),UpdatedAt=new DateTime(2026,1,1)});});
  b.Entity<ProductRaw>(e=>{e.ToTable("product_raw");e.Property(x=>x.SkuName).HasMaxLength(200);e.Property(x=>x.BaseUnit).HasMaxLength(10);e.Property(x=>x.BoxUnit).HasMaxLength(10);e.Property(x=>x.SpecStr).HasMaxLength(50);e.Property(x=>x.ImageUrl).HasMaxLength(500);e.Property(x=>x.BoxPrice).HasPrecision(10,2);e.Property(x=>x.UnitPrice).HasPrecision(10,4);e.Property(x=>x.BrandName).HasMaxLength(100);e.Property(x=>x.CategoryName1).HasMaxLength(50);e.Property(x=>x.CategoryName2).HasMaxLength(50);e.Property(x=>x.Height).HasPrecision(8,2);e.Property(x=>x.Length).HasPrecision(8,2);e.Property(x=>x.Width).HasPrecision(8,2);e.HasIndex(x=>x.SkuId).IsUnique();e.HasIndex(x=>x.BrandIdRaw);e.HasIndex(x=>x.CategoryCode1);e.HasIndex(x=>x.CategoryCode2);});
  b.Entity<SyncTaskLog>(e=>{e.ToTable("sync_task_log");e.Property(x=>x.TaskType).HasMaxLength(50);e.Property(x=>x.ErrorMessage).HasMaxLength(2000);e.HasIndex(x=>new{x.TaskType,x.Status,x.StartedAt});}); b.Entity<DailySales>(e=>{e.ToTable("daily_sales");e.Property(x=>x.TotalAmount).HasPrecision(12,2);e.HasIndex(x=>new{x.MachineId,x.SalesDate}).IsUnique();e.HasIndex(x=>x.SalesDate);e.HasOne(x=>x.Machine).WithMany().HasForeignKey(x=>x.MachineId);}); }
 public override Task<int> SaveChangesAsync(CancellationToken ct=default) { foreach(var entry in ChangeTracker.Entries<Entity>()) { if(entry.State==EntityState.Added) entry.Entity.CreatedAt=entry.Entity.UpdatedAt=DateTime.Now; else if(entry.State==EntityState.Modified) entry.Entity.UpdatedAt=DateTime.Now; } return base.SaveChangesAsync(ct); }
}
