// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingStock.Api.Infrastructure;

#nullable disable

namespace VendingStock.Api.Infrastructure.Migrations
{
    [DbContext(typeof(VendingStockDbContext))]
    [Migration("20260715150313_AddProductRawGoodsSync")]
    partial class AddProductRawGoodsSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VendingStock.Api.Domain.DeliveryOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_time");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveryEndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_end_time");

                    b.Property<long>("DeliveryPersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_person_id");

                    b.Property<DateTime?>("DeliveryStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_start_time");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_id");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("order_no");

                    b.Property<long>("RestockerId")
                        .HasColumnType("bigint")
                        .HasColumnName("restocker_id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_delivery_order");

                    b.HasIndex("DeliveryPersonId")
                        .HasDatabaseName("ix_delivery_order_delivery_person_id");

                    b.HasIndex("OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_order_order_no");

                    b.HasIndex("RestockerId")
                        .HasDatabaseName("ix_delivery_order_restocker_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_delivery_order_vehicle_id");

                    b.HasIndex("MachineId", "Status")
                        .HasDatabaseName("ix_delivery_order_machine_id_status");

                    b.ToTable("delivery_order", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.DeliveryOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<long>("SourceWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_warehouse_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_delivery_order_item");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_delivery_order_item_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_delivery_order_item_product_id");

                    b.HasIndex("SourceWarehouseId")
                        .HasDatabaseName("ix_delivery_order_item_source_warehouse_id");

                    b.ToTable("delivery_order_item", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.InventoryTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int")
                        .HasColumnName("quantity_after");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("int")
                        .HasColumnName("quantity_before");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int")
                        .HasColumnName("quantity_change");

                    b.Property<string>("RelatedOrderNo")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("related_order_no");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long?>("WarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transaction");

                    b.HasIndex("WarehouseId", "ProductId")
                        .HasDatabaseName("ix_inventory_transaction_warehouse_id_product_id");

                    b.ToTable("inventory_transaction", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.MachineProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AllocationQuantity")
                        .HasColumnType("int")
                        .HasColumnName("allocation_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("SellPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("sell_price");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_machine_product");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_machine_product_product_id");

                    b.HasIndex("MachineId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_machine_product_machine_id_product_id");

                    b.ToTable("machine_product", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<long>("SpecId")
                        .HasColumnType("bigint")
                        .HasColumnName("spec_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_product_brand_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category_id");

                    b.HasIndex("SpecId")
                        .HasDatabaseName("ix_product_spec_id");

                    b.HasIndex("Name", "SpecId", "BrandId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_name_spec_id_brand_id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.ProductBrand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product_brand");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_brand_name");

                    b.ToTable("product_brand", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_category_name");

                    b.ToTable("product_category", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.ProductRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseUnit")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("base_unit");

                    b.Property<decimal?>("BoxPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("box_price");

                    b.Property<int?>("BoxQuantity")
                        .HasColumnType("int")
                        .HasColumnName("box_quantity");

                    b.Property<string>("BoxUnit")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("box_unit");

                    b.Property<int?>("BrandIdRaw")
                        .HasColumnType("int")
                        .HasColumnName("brand_id_raw");

                    b.Property<string>("BrandName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brand_name");

                    b.Property<int?>("CategoryCode1")
                        .HasColumnType("int")
                        .HasColumnName("category_code1");

                    b.Property<int?>("CategoryCode2")
                        .HasColumnType("int")
                        .HasColumnName("category_code2");

                    b.Property<string>("CategoryName1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name1");

                    b.Property<string>("CategoryName2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Height")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("height");

                    b.Property<bool>("Hot")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("hot");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsRecentlyPurchased")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_recently_purchased");

                    b.Property<decimal?>("Length")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("length");

                    b.Property<int?>("PackageNum")
                        .HasColumnType("int")
                        .HasColumnName("package_num");

                    b.Property<int>("SkuId")
                        .HasColumnType("int")
                        .HasColumnName("sku_id");

                    b.Property<string>("SkuName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sku_name");

                    b.Property<string>("SpecStr")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("spec_str");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("StockA")
                        .HasColumnType("int")
                        .HasColumnName("stock_a");

                    b.Property<int>("StockB")
                        .HasColumnType("int")
                        .HasColumnName("stock_b");

                    b.Property<int>("StockP")
                        .HasColumnType("int")
                        .HasColumnName("stock_p");

                    b.Property<int>("StockR")
                        .HasColumnType("int")
                        .HasColumnName("stock_r");

                    b.Property<int>("StockW")
                        .HasColumnType("int")
                        .HasColumnName("stock_w");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("Width")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_product_raw");

                    b.HasIndex("BrandIdRaw")
                        .HasDatabaseName("ix_product_raw_brand_id_raw");

                    b.HasIndex("CategoryCode1")
                        .HasDatabaseName("ix_product_raw_category_code1");

                    b.HasIndex("CategoryCode2")
                        .HasDatabaseName("ix_product_raw_category_code2");

                    b.HasIndex("SkuId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_raw_sku_id");

                    b.ToTable("product_raw", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.ProductSpec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product_spec");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_spec_name");

                    b.ToTable("product_spec", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryPerson")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("delivery_person");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("import_time");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("order_no");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("receiver");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int")
                        .HasColumnName("total_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order");

                    b.HasIndex("OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_order_order_no");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_purchase_order_warehouse_id_status");

                    b.ToTable("purchase_order", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.PurchaseOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_item");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_purchase_order_item_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_order_item_product_id");

                    b.ToTable("purchase_order_item", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.Staff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_staff_role");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.SyncTaskLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_count");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int")
                        .HasColumnName("success_count");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_type");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int")
                        .HasColumnName("total_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sync_task_log");

                    b.HasIndex("TaskType", "Status", "StartedAt")
                        .HasDatabaseName("ix_sync_task_log_task_type_status_started_at");

                    b.ToTable("sync_task_log", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.SysConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("config_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sys_config");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_config_config_key");

                    b.ToTable("sys_config", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConfigKey = "restock_threshold_percent",
                            ConfigValue = "50",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "补货阈值百分比(低于此比例需补货)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VendingStock.Api.Domain.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plate_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_vehicle");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_plate_number");

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.VendingMachine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("machine_code");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("manager");

                    b.Property<string>("ManagerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("manager_phone");

                    b.Property<DateTime>("OnlineTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("online_time");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_vending_machine");

                    b.HasIndex("MachineCode")
                        .IsUnique()
                        .HasDatabaseName("ix_vending_machine_machine_code");

                    b.ToTable("vending_machine", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("manager");

                    b.Property<string>("ManagerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("manager_phone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_warehouse");

                    b.ToTable("warehouse", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.WarehouseStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_stock");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_warehouse_stock_product_id");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouse_stock_warehouse_id_product_id");

                    b.ToTable("warehouse_stock", (string)null);
                });

            modelBuilder.Entity("VendingStock.Api.Domain.DeliveryOrder", b =>
                {
                    b.HasOne("VendingStock.Api.Domain.Staff", "DeliveryPerson")
                        .WithMany()
                        .HasForeignKey("DeliveryPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_order_staff_delivery_person_id");

                    b.HasOne("VendingStock.Api.Domain.VendingMachine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_order_vending_machine_machine_id");

                    b.HasOne("VendingStock.Api.Domain.Staff", "Restocker")
                        .WithMany()
                        .HasForeignKey("RestockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_order_staff_restocker_id");

                    b.HasOne("VendingStock.Api.Domain.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_delivery_order_vehicle_vehicle_id");

                    b.Navigation("DeliveryPerson");

                    b.Navigation("Machine");

                    b.Navigation("Restocker");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.DeliveryOrderItem", b =>
                {
                    b.HasOne("VendingStock.Api.Domain.DeliveryOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_order_item_delivery_order_order_id");

                    b.HasOne("VendingStock.Api.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_order_item_product_product_id");

                    b.HasOne("VendingStock.Api.Domain.Warehouse", "SourceWarehouse")
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_order_item_warehouse_source_warehouse_id");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.MachineProduct", b =>
                {
                    b.HasOne("VendingStock.Api.Domain.VendingMachine", "Machine")
                        .WithMany("Products")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_machine_product_vending_machine_machine_id");

                    b.HasOne("VendingStock.Api.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_machine_product_product_product_id");

                    b.Navigation("Machine");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.Product", b =>
                {
                    b.HasOne("VendingStock.Api.Domain.ProductBrand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_product_brand_brand_id");

                    b.HasOne("VendingStock.Api.Domain.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_product_category_category_id");

                    b.HasOne("VendingStock.Api.Domain.ProductSpec", "Spec")
                        .WithMany("Products")
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_product_spec_spec_id");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.PurchaseOrder", b =>
                {
                    b.HasOne("VendingStock.Api.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_warehouse_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.PurchaseOrderItem", b =>
                {
                    b.HasOne("VendingStock.Api.Domain.PurchaseOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_item_purchase_order_order_id");

                    b.HasOne("VendingStock.Api.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_item_product_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.WarehouseStock", b =>
                {
                    b.HasOne("VendingStock.Api.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_stock_product_product_id");

                    b.HasOne("VendingStock.Api.Domain.Warehouse", "Warehouse")
                        .WithMany("Stocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_stock_warehouse_warehouse_id");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.DeliveryOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.ProductBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.ProductSpec", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.VendingMachine", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VendingStock.Api.Domain.Warehouse", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
