using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VendingStock.Api.Infrastructure.Migrations
{
    public partial class AddMachinesAndDelivery : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"CREATE TABLE vending_machine (id BIGINT NOT NULL AUTO_INCREMENT, machine_code VARCHAR(50) NOT NULL, address VARCHAR(200) NOT NULL, online_time DATETIME(6) NOT NULL, status TINYINT UNSIGNED NOT NULL, manager VARCHAR(50) NOT NULL, manager_phone VARCHAR(20) NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, CONSTRAINT pk_vending_machine PRIMARY KEY (id), CONSTRAINT ak_vending_machine_machine_code UNIQUE (machine_code)) CHARACTER SET utf8mb4;");
            migrationBuilder.Sql(@"CREATE TABLE staff (id BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(50) NOT NULL, phone VARCHAR(20) NOT NULL, address VARCHAR(200) NULL, role TINYINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, CONSTRAINT pk_staff PRIMARY KEY (id)) CHARACTER SET utf8mb4;");
            migrationBuilder.Sql(@"CREATE TABLE vehicle (id BIGINT NOT NULL AUTO_INCREMENT, plate_number VARCHAR(20) NOT NULL, vehicle_type VARCHAR(50) NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, CONSTRAINT pk_vehicle PRIMARY KEY (id), CONSTRAINT ak_vehicle_plate_number UNIQUE (plate_number)) CHARACTER SET utf8mb4;");
            migrationBuilder.Sql(@"CREATE TABLE sys_config (id BIGINT NOT NULL AUTO_INCREMENT, config_key VARCHAR(100) NOT NULL, config_value VARCHAR(500) NOT NULL, description VARCHAR(200) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, CONSTRAINT pk_sys_config PRIMARY KEY (id), CONSTRAINT ak_sys_config_config_key UNIQUE (config_key)) CHARACTER SET utf8mb4;");
            migrationBuilder.Sql(@"CREATE TABLE machine_product (id BIGINT NOT NULL AUTO_INCREMENT, machine_id BIGINT NOT NULL, product_id BIGINT NOT NULL, stock_quantity INT NOT NULL, allocation_quantity INT NOT NULL, sell_price DECIMAL(10,2) NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, CONSTRAINT pk_machine_product PRIMARY KEY (id), CONSTRAINT fk_machine_product_vending_machine_machine_id FOREIGN KEY (machine_id) REFERENCES vending_machine(id) ON DELETE CASCADE, CONSTRAINT fk_machine_product_product_product_id FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE, CONSTRAINT ak_machine_product_machine_id_product_id UNIQUE (machine_id, product_id)) CHARACTER SET utf8mb4;");
            migrationBuilder.Sql(@"CREATE TABLE delivery_order (id BIGINT NOT NULL AUTO_INCREMENT, order_no VARCHAR(32) NOT NULL, machine_id BIGINT NOT NULL, restocker_id BIGINT NOT NULL, delivery_person_id BIGINT NOT NULL, vehicle_id BIGINT NULL, status TINYINT UNSIGNED NOT NULL, completed_time DATETIME(6) NULL, delivery_start_time DATETIME(6) NULL, delivery_end_time DATETIME(6) NULL, cancelled_time DATETIME(6) NULL, cancel_reason VARCHAR(500) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, CONSTRAINT pk_delivery_order PRIMARY KEY (id), CONSTRAINT fk_delivery_order_vending_machine_machine_id FOREIGN KEY (machine_id) REFERENCES vending_machine(id) ON DELETE CASCADE, CONSTRAINT fk_delivery_order_staff_restocker_id FOREIGN KEY (restocker_id) REFERENCES staff(id) ON DELETE RESTRICT, CONSTRAINT fk_delivery_order_staff_delivery_person_id FOREIGN KEY (delivery_person_id) REFERENCES staff(id) ON DELETE RESTRICT, CONSTRAINT fk_delivery_order_vehicle_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicle(id) ON DELETE SET NULL, CONSTRAINT ak_delivery_order_order_no UNIQUE (order_no)) CHARACTER SET utf8mb4;");
            migrationBuilder.Sql(@"CREATE TABLE delivery_order_item (id BIGINT NOT NULL AUTO_INCREMENT, order_id BIGINT NOT NULL, product_id BIGINT NOT NULL, source_warehouse_id BIGINT NOT NULL, quantity INT NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, CONSTRAINT pk_delivery_order_item PRIMARY KEY (id), CONSTRAINT fk_delivery_order_item_delivery_order_order_id FOREIGN KEY (order_id) REFERENCES delivery_order(id) ON DELETE CASCADE, CONSTRAINT fk_delivery_order_item_product_product_id FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE, CONSTRAINT fk_delivery_order_item_warehouse_source_warehouse_id FOREIGN KEY (source_warehouse_id) REFERENCES warehouse(id) ON DELETE CASCADE) CHARACTER SET utf8mb4;");
            migrationBuilder.Sql("CREATE INDEX ix_staff_role ON staff (role); CREATE INDEX ix_machine_product_product_id ON machine_product (product_id); CREATE INDEX ix_delivery_order_machine_id_status ON delivery_order (machine_id, status); CREATE INDEX ix_delivery_order_restocker_id ON delivery_order (restocker_id); CREATE INDEX ix_delivery_order_delivery_person_id ON delivery_order (delivery_person_id); CREATE INDEX ix_delivery_order_item_product_id ON delivery_order_item (product_id); CREATE INDEX ix_delivery_order_item_source_warehouse_id ON delivery_order_item (source_warehouse_id);");
            migrationBuilder.Sql("INSERT INTO sys_config (id, config_key, config_value, description, created_at, updated_at) VALUES (1, 'restock_threshold_percent', '50', '补货阈值百分比(低于此比例需补货)', '2026-01-01 00:00:00', '2026-01-01 00:00:00');");
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS delivery_order_item; DROP TABLE IF EXISTS delivery_order; DROP TABLE IF EXISTS machine_product; DROP TABLE IF EXISTS sys_config; DROP TABLE IF EXISTS vehicle; DROP TABLE IF EXISTS staff; DROP TABLE IF EXISTS vending_machine;");
        }
    }
}
