using Microsoft.EntityFrameworkCore;
using VendingStock.Api.Common;
using VendingStock.Api.Domain;
using VendingStock.Api.Infrastructure;
namespace VendingStock.Api.Services;
public sealed class DeliveryService(VendingStockDbContext db)
{
 public async Task CompleteRestockAsync(long id,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var order=await db.DeliveryOrders.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("配货单不存在",4040);if(order.Status!=DeliveryOrderStatus.Pending)throw new BusinessException("当前状态不能确认配货完成");foreach(var item in order.Items){var stock=await db.WarehouseStocks.SingleOrDefaultAsync(x=>x.WarehouseId==item.SourceWarehouseId&&x.ProductId==item.ProductId,ct)??throw new BusinessException("来源仓库不存在该商品库存");if(stock.Quantity<item.Quantity)throw new BusinessException("来源仓库库存不足");var before=stock.Quantity;stock.Quantity-=item.Quantity;db.InventoryTransactions.Add(new InventoryTransaction{TransactionType=InventoryTransactionType.DeliveryFromWarehouse,WarehouseId=item.SourceWarehouseId,ProductId=item.ProductId,QuantityChange=-item.Quantity,QuantityBefore=before,QuantityAfter=stock.Quantity,RelatedOrderNo=order.OrderNo,Remark="确认配货完成，仓库出库"});}order.Status=DeliveryOrderStatus.RestockCompleted;order.CompletedTime=DateTime.Now;await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}
 public async Task StartDeliveryAsync(long id,CancellationToken ct){var order=await db.DeliveryOrders.FindAsync([id],ct)??throw new BusinessException("配货单不存在",4040);if(order.Status!=DeliveryOrderStatus.RestockCompleted)throw new BusinessException("当前状态不能开始送货");order.Status=DeliveryOrderStatus.Delivering;order.DeliveryStartTime=DateTime.Now;await db.SaveChangesAsync(ct);}
 public async Task CompleteDeliveryAsync(long id,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var order=await db.DeliveryOrders.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new BusinessException("配货单不存在",4040);if(order.Status!=DeliveryOrderStatus.Delivering)throw new BusinessException("当前状态不能确认送货完成");foreach(var item in order.Items){var machineProduct=await db.MachineProducts.SingleOrDefaultAsync(x=>x.MachineId==order.MachineId&&x.ProductId==item.ProductId,ct)??throw new BusinessException("贩卖机未配置该商品");var before=machineProduct.StockQuantity;machineProduct.StockQuantity+=item.Quantity;db.InventoryTransactions.Add(new InventoryTransaction{TransactionType=InventoryTransactionType.DeliveryToMachine,ProductId=item.ProductId,QuantityChange=item.Quantity,QuantityBefore=before,QuantityAfter=machineProduct.StockQuantity,RelatedOrderNo=order.OrderNo,Remark="送货完成，商品入机"});}order.Status=DeliveryOrderStatus.Delivered;order.DeliveryEndTime=DateTime.Now;await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}
 public async Task CancelAsync(long id,string reason,CancellationToken ct){var order=await db.DeliveryOrders.FindAsync([id],ct)??throw new BusinessException("配货单不存在",4040);if(order.Status!=DeliveryOrderStatus.Pending)throw new BusinessException("仅待配货单可取消");order.Status=DeliveryOrderStatus.Cancelled;order.CancelledTime=DateTime.Now;order.CancelReason=reason;await db.SaveChangesAsync(ct);}
}
