namespace VendingStock.Api.Domain;
public abstract class Entity { public long Id { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }
public sealed class ProductCategory : Entity { public string Name { get; set; } = null!; public int SortOrder { get; set; } public ICollection<Product> Products { get; set; } = []; }
public sealed class ProductSpec : Entity { public string Name { get; set; } = null!; public int SortOrder { get; set; } public ICollection<Product> Products { get; set; } = []; }
public sealed class ProductBrand : Entity { public string Name { get; set; } = null!; public int SortOrder { get; set; } public ICollection<Product> Products { get; set; } = []; }
public sealed class Product : Entity { public string Name { get; set; } = null!; public long SpecId { get; set; } public ProductSpec Spec { get; set; } = null!; public long BrandId { get; set; } public ProductBrand Brand { get; set; } = null!; public long CategoryId { get; set; } public ProductCategory Category { get; set; } = null!; public decimal Price { get; set; } public int? Weight { get; set; } public string? ImageUrl { get; set; } }
public sealed class Warehouse : Entity { public string Name { get; set; } = null!; public string Address { get; set; } = null!; public string Manager { get; set; } = null!; public string ManagerPhone { get; set; } = null!; public ICollection<WarehouseStock> Stocks { get; set; } = []; }
public sealed class WarehouseStock : Entity { public long WarehouseId { get; set; } public Warehouse Warehouse { get; set; } = null!; public long ProductId { get; set; } public Product Product { get; set; } = null!; public int Quantity { get; set; } public string? Tags { get; set; } }
public sealed class PurchaseOrder : Entity { public string OrderNo { get; set; } = null!; public long WarehouseId { get; set; } public Warehouse Warehouse { get; set; } = null!; public DateTime ImportTime { get; set; } public string DeliveryPerson { get; set; } = null!; public string Receiver { get; set; } = null!; public int TotalQuantity { get; set; } public PurchaseOrderStatus Status { get; set; } public ICollection<PurchaseOrderItem> Items { get; set; } = []; }
public sealed class PurchaseOrderItem : Entity { public long OrderId { get; set; } public PurchaseOrder Order { get; set; } = null!; public long ProductId { get; set; } public Product Product { get; set; } = null!; public int Quantity { get; set; } }
public enum PurchaseOrderStatus : byte { Pending = 0, Imported = 1 }
public sealed class InventoryTransaction : Entity { public InventoryTransactionType TransactionType { get; set; } public long? WarehouseId { get; set; } public long ProductId { get; set; } public int QuantityChange { get; set; } public int QuantityBefore { get; set; } public int QuantityAfter { get; set; } public string? RelatedOrderNo { get; set; } public string? Remark { get; set; } }
public enum InventoryTransactionType : byte { PurchaseImport = 1, ManualAdjustment = 2, DeliveryFromWarehouse = 3, DeliveryToMachine = 4 }

public sealed class VendingMachine : Entity { public string MachineCode { get; set; } = null!; public string Address { get; set; } = null!; public DateTime OnlineTime { get; set; } public VendingMachineStatus Status { get; set; } public string Manager { get; set; } = null!; public string ManagerPhone { get; set; } = null!; public ICollection<MachineProduct> Products { get; set; } = []; }
public enum VendingMachineStatus : byte { Normal = 0, Fault = 1, UnderMaintenance = 2 }
public sealed class MachineProduct : Entity { public long MachineId { get; set; } public VendingMachine Machine { get; set; } = null!; public long ProductId { get; set; } public Product Product { get; set; } = null!; public int StockQuantity { get; set; } public int AllocationQuantity { get; set; } public decimal SellPrice { get; set; } }
public sealed class Staff : Entity { public string Name { get; set; } = null!; public string Phone { get; set; } = null!; public string? Address { get; set; } public StaffRole Role { get; set; } }
public enum StaffRole : byte { Restocker = 1, DeliveryPerson = 2 }
public sealed class Vehicle : Entity { public string PlateNumber { get; set; } = null!; public string VehicleType { get; set; } = null!; }
public sealed class DeliveryOrder : Entity { public string OrderNo { get; set; } = null!; public long MachineId { get; set; } public VendingMachine Machine { get; set; } = null!; public long RestockerId { get; set; } public Staff Restocker { get; set; } = null!; public long DeliveryPersonId { get; set; } public Staff DeliveryPerson { get; set; } = null!; public long? VehicleId { get; set; } public Vehicle? Vehicle { get; set; } public DeliveryOrderStatus Status { get; set; } public DateTime? CompletedTime { get; set; } public DateTime? DeliveryStartTime { get; set; } public DateTime? DeliveryEndTime { get; set; } public DateTime? CancelledTime { get; set; } public string? CancelReason { get; set; } public ICollection<DeliveryOrderItem> Items { get; set; } = []; }
public enum DeliveryOrderStatus : byte { Pending = 0, RestockCompleted = 1, Delivering = 2, Delivered = 3, Cancelled = 4 }
public sealed class DeliveryOrderItem : Entity { public long OrderId { get; set; } public DeliveryOrder Order { get; set; } = null!; public long ProductId { get; set; } public Product Product { get; set; } = null!; public long SourceWarehouseId { get; set; } public Warehouse SourceWarehouse { get; set; } = null!; public int Quantity { get; set; } }
public sealed class SysConfig : Entity { public string ConfigKey { get; set; } = null!; public string ConfigValue { get; set; } = null!; public string? Description { get; set; } }

public sealed class ProductRaw : Entity { public int SkuId { get; set; } public string SkuName { get; set; } = null!; public string? BaseUnit { get; set; } public string? BoxUnit { get; set; } public int? BoxQuantity { get; set; } public string? SpecStr { get; set; } public string? ImageUrl { get; set; } public decimal? BoxPrice { get; set; } public decimal? UnitPrice { get; set; } public bool Hot { get; set; } public int? PackageNum { get; set; } public bool IsRecentlyPurchased { get; set; } public int Stock { get; set; } public int StockR { get; set; } public int StockP { get; set; } public int StockA { get; set; } public int StockB { get; set; } public int StockW { get; set; } public int? BrandIdRaw { get; set; } public string? BrandName { get; set; } public int? CategoryCode1 { get; set; } public string? CategoryName1 { get; set; } public int? CategoryCode2 { get; set; } public string? CategoryName2 { get; set; } public decimal? Height { get; set; } public decimal? Length { get; set; } public decimal? Width { get; set; } }
public sealed class SyncTaskLog : Entity { public string TaskType { get; set; } = null!; public SyncTaskStatus Status { get; set; } public DateTime StartedAt { get; set; } public DateTime? FinishedAt { get; set; } public int TotalCount { get; set; } public int SuccessCount { get; set; } public int FailedCount { get; set; } public string? ErrorMessage { get; set; } }
public enum SyncTaskStatus : byte { Running = 0, Success = 1, Failed = 2 }

public sealed class DailySales : Entity { public long MachineId { get; set; } public VendingMachine Machine { get; set; } = null!; public DateOnly SalesDate { get; set; } public decimal TotalAmount { get; set; } }
